### ISSUE TITLE
map die minimap

### ISSUE THREAD

**Issue by Reptudn** [FreddyMSchubert/42_cub3d#41]

**Comment by FreddyMSchubert** [comment]
oh no the poor map why did it die.

no but really what?

**Comment by Reptudn** [comment]
> oh no the poor map why did it die.
> 
> no but really what?

what u talking about?

**Comment by FreddyMSchubert** [comment]
Minimap works and looks good, couple issues:

1. The colors are very unpleasant.
2. The minimap doesn't show always when walking for some reason.

This issues shall be ironed out on another branch though, for now it's good our progress is unified.
