### ISSUE TITLE
bro die MLX Documentation ist ass

### ISSUE THREAD

**Issue by NoelSabia** [FreddyMSchubert/42_cub3d#51]
Deswegen bin ich hier, nen Plan wie ich den floor und ceiling gescheit machen kann bzw. was nutzt ihr dafuer (sprich mlx_put_pixel oder welche Funktion?Vllt gibt es sowas wie z-Achsen layering was ich vllt uebersehen habe oder so?

**Comment by FreddyMSchubert** [comment]
Die library ist ja darauf ausgelegt dass du alles selber machen musst. Aber zu erwarten dass du direkt mit OpenGL / glfw interagierst ist halt bissl far, deswegen eine dünne abstraktionslayer. Gibt keine z-layering, gotta do that yourself.
Wir machen floor und ceiling in src/2_setup/setup_mlx.c - halt einfach ein eigener layer der als erstes auf das window gepackt wird. You gotta redo it when the window gets resized though.

**Comment by FreddyMSchubert** [comment]
Und die MLX42 documentation ist massiv super, hast du mal die minilibx documentation gelesen? Ich auch nicht, it doesn't exist. Here we have 10 solid markdown files.

**Comment by NoelSabia** [comment]
To be fair, ich muss noch ein bisschen in die documentation reinlesen, ABER der Tipp mit dem floor ist schon cool, spart Rechenleistung, danke 😄
